#log parser config
---
travisCommand:
  start: 'travis_fold:start'
  end: 'travis_fold:end'
  extract: 'travis_fold:start:(.*)'

reactor:
  summaryStart: 'Reactor Summary'
  summaryEnd: '------'
  extractRegex: "([[\\w]*[\\s|-|:]]+)[\\.]+([[\\w]*[\\s|-|:]]+)"

parsingRuleGroups:
  cleanString:
    - remove_ending_point
    - remove_help_block
    - remove_path
    - remove_projects
    - remove_url
    - remove_arguments
    - remove_ending_point
    - remove_ending_whitespaces
    - remove_commas
    - remove_double_whitespaces
    - remove_non_letter_chars
  cleanError:
    - extract_error_cause

parsingRules:
  remove_commas:
    pattern: ','
    replacement: ''
    type: STRING
  remove_whitespace:
    pattern: '\s'
    replacement: ''
    type: REGEX
  remove_double_whitespaces:
    pattern: '\s+'
    replacement: ' '
    type: REGEX
  remove_ending_whitespaces:
    pattern: '\s+$'
    replacement: ''
    type: REGEX
  remove_url:
    pattern: '(https?|ftp|gopher|telnet|file|Unsure|http):'
    replacement: ''
    type: REGEX
  remove_arguments:
    pattern: '-\S+'
    replacement: ''
    type: REGEX
  remove_non_letter_chars:
    pattern: '[^a-zA-Z0-9\s:]+'
    replacement: ''
    type: REGEX
  remove_path:
    pattern: '(/\S+)+'
    replacement: ''
    type: REGEX
  remove_projects:
    pattern: '\S*[.|:]+\S+'
    replacement: ''
    type: REGEX
  remove_help_block:
    pattern: '-> [Help 1]'
    replacement: ''
    type: STRING
  remove_ending_point:
    pattern: '\.+$'
    replacement: ''
    type: REGEX
  extract_goal:
    pattern: 'goal \S*[.|:]?\S*'
    replacement: 'goal '
    type: REGEX
  extract_error_cause:
    pattern: 'on project\s[\S]+:'
    replacement: 'on project'
    type: REGEX
  replace_double_point_stackoverflow:
    pattern: ':'
    replacement: '\\'
    type: STRING

stopWords:
  - "a"
  - "about"
  - "above"
  - "after"
  - "again"
  - "against"
  - "all"
  - "am"
  - "an"
  - "and"
  - "any"
  - "are"
  - "aren't"
  - "as"
  - "at"
  - "be"
  - "because"
  - "been"
  - "before"
  - "being"
  - "below"
  - "between"
  - "both"
  - "but"
  - "by"
  - "can't"
  - "cannot"
  - "could"
  - "couldn't"
  - "did"
  - "didn't"
  - "do"
  - "does"
  - "doesn't"
  - "doing"
  - "don't"
  - "down"
  - "during"
  - "each"
  - "few"
  - "for"
  - "from"
  - "further"
  - "had"
  - "hadn't"
  - "has"
  - "hasn't"
  - "have"
  - "haven't"
  - "having"
  - "he"
  - "he'd"
  - "he'll"
  - "he's"
  - "her"
  - "here"
  - "here's"
  - "hers"
  - "herself"
  - "him"
  - "himself"
  - "his"
  - "how"
  - "how's"
  - "i"
  - "i'd"
  - "i'll"
  - "i'm"
  - "i've"
  - "if"
  - "in"
  - "into"
  - "is"
  - "isn't"
  - "it"
  - "it's"
  - "its"
  - "itself"
  - "let's"
  - "me"
  - "more"
  - "most"
  - "mustn't"
  - "my"
  - "myself"
  - "no"
  - "nor"
  - "not"
  - "of"
  - "off"
  - "on"
  - "once"
  - "only"
  - "or"
  - "other"
  - "ought"
  - "our"
  - "ours"
  - "ourrselves"
  - "out"
  - "over"
  - "own"
  - "same"
  - "shan't"
  - "she"
  - "she'd"
  - "she'll"
  - "she's"
  - "should"
  - "shouldn't"
  - "so"
  - "some"
  - "such"
  - "than"
  - "that"
  - "that's"
  - "the"
  - "their"
  - "theirs"
  - "them"
  - "themselves"
  - "then"
  - "there"
  - "there's"
  - "these"
  - "they"
  - "they'd"
  - "they'll"
  - "they're"
  - "they've"
  - "this"
  - "those"
  - "through"
  - "to"
  - "too"
  - "under"
  - "until"
  - "up"
  - "very"
  - "was"
  - "wasn't"
  - "we"
  - "we'd"
  - "we'll"
  - "we're"
  - "we've"
  - "were"
  - "weren't"
  - "what"
  - "what's"
  - "when"
  - "when's"
  - "where"
  - "where's"
  - "which"
  - "while"
  - "who"
  - "who's"
  - "whom"
  - "why"
  - "why's"
  - "with"
  - "won't"
  - "would"
  - "wouldn't"
  - "you"
  - "you'd"
  - "you'll"
  - "you're"
  - "you've"
  - "your"
  - "yours"
  - "yourself"
  - "yourselves"
  - "warning"
  - "error"